### ISSUE TITLE
adal.adal_error.AdalError: Unexpected polling state invalid_request

### ISSUE THREAD

**Issue by dannybritto96** [AzureAD/azure-activedirectory-library-for-python#170]
Traceback (most recent call last):
  File "ms.py", line 45, in <module>
    session = device_flow_session(CLIENT_ID)
  File "ms.py", line 36, in device_flow_session
    token_response = ctx.acquire_token_with_device_code(RESOURCE,device_code,client_id)
  File "/home/danny/.local/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/danny/.local/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/danny/.local/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/danny/.local/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/danny/.local/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state invalid_request

The program was working just fine till yesterday and out of the blue I'm getting this error. 
Line causing the error 
`token_response = ctx.acquire_token_with_device_code(RESOURCE,device_code,client_id)`

**Comment by dannybritto96** [comment]
Version issue. Works on Graph API Beta.
